# FOSSology Docker Compose file
# Copyright Siemens AG 2016
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.

version: '2'
services:
  fossology-base:
    build:
      context: ..
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: fossology
