# FOSSology Docker Compose file
# Copyright Siemens AG 2016, fabio.huser@siemens.com
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
#
# Description: Recipe for setting up a multi container FOSSology
#              Docker setup with separate Database instance

version: '2'
services:
  # scheduler:
  #   build: ..
  #   environment:
  #     - FOSSOLOGY_DB_HOST=db
  #     - FOSSOLOGY_DB_NAME=fossology
  #     - FOSSOLOGY_DB_USER=fossy
  #     - FOSSOLOGY_DB_PASSWORD=fossy
  #   command: scheduler
  #   links:
  #     - db
  web:
    build: ..
    environment:
      - FOSSOLOGY_DB_HOST=db
      - FOSSOLOGY_DB_NAME=fossology
      - FOSSOLOGY_DB_USER=fossy
      - FOSSOLOGY_DB_PASSWORD=fossy
      - SW360_PUBLIC_KEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDcGNLLHWOmLZZbm9Kr+3ygMY6WJIEh6v6ywYaE/9WNz0ri9bojwtfyMTMCeOOcrUd+oKz2QZJi22isxFCU3MkN6JN/+1nCDEqRUu36jg5uNwEklzNa4zbJcHao5UynKK0JpEHFI08ZIrJsDGdmPw/C3j8+Jlcye9QA9dA/Sr6KRRUVN+5gnP4MJKyhJ3dOVBv0tlh8AmwN1zlam+F6lmHsv2pK/IGqNQTVshkbL/S3yjWethxQXEjhmAZbzeV5VSbfRlcnA4wyX4ktsfAVJXQmVH3stYG8N0hRKb6yun2q8SPjPngBMObLZu/uml12GQPqC1odgstYw8SoSn7CiNQd sw360@sw360
    command: web
    ports:
      - 8081:80
      - 2222:2222
    links:
      - db
    # volumes_from:
    #   - scheduler
  db:
    image: postgres
    environment:
      - POSTGRES_DB=fossology
      - POSTGRES_USER=fossy
      - POSTGRES_PASSWORD=fossy
      - POSTGRES_INITDB_ARGS='-E SQL_ASCII'
