# FOSSology Docker Compose file
# Copyright Siemens AG 2016, fabio.huser@siemens.com, maximilian.huber@tngtech.com
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered as-is,
# without any warranty.
#
# Description: Recipe for setting up a multi container FOSSology
#              Docker setup with separate Database instance

version: '2'
services:
  fossology-base:
    build:
      context: ../..
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: fossology-base
    environment:
      - FOSSOLOGY_DB_HOST=fossology-db
      - FOSSOLOGY_DB_NAME=fossology
      - FOSSOLOGY_DB_USER=fossy
      - FOSSOLOGY_DB_PASSWORD=fossy
    command: /usr/local/lib/fossology/dbcreate
    links:
      - fossology-db
  fossology-scheduler:
    build:
      context: fossology-scheduler
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: fossology-scheduler
    restart: unless-stopped
    environment:
      - FOSSOLOGY_DB_HOST=fossology-db
      - FOSSOLOGY_DB_NAME=fossology
      - FOSSOLOGY_DB_USER=fossy
      - FOSSOLOGY_DB_PASSWORD=fossy
    command: scheduler
    links:
      - fossology-base
      - fossology-db
    # volumes:
    #   - ./_repository:/srv/fossology/repository/
  fossology-web:
    build:
      context: fossology-web
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: fossology-web
    restart: unless-stopped
    environment:
      - FOSSOLOGY_DB_HOST=fossology-db
      - FOSSOLOGY_DB_NAME=fossology
      - FOSSOLOGY_DB_USER=fossy
      - FOSSOLOGY_DB_PASSWORD=fossy
      - FOSSOLOGY_SCHEDULER_HOST=fossology-scheduler
    command: web
    ports:
      - 8081:8080
    links:
      - fossology-base # build base image
      - fossology-db
      - fossology-scheduler
    volumes_from:
      - fossology-scheduler
  # fossology-repository:
  #   ...
  fossology-db:
    image: postgres
    # build:
    #   context: fossology-db
    # image: fossology-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=fossology
      - POSTGRES_USER=fossy
      - POSTGRES_PASSWORD=fossy
      - POSTGRES_INITDB_ARGS='-E SQL_ASCII'
  # fossology-sw360-connector:
  #   ...
  #   command: sshd
  #   ports:
  #     - 2222:22
